### ISSUE TITLE
Unable to create a new label

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/tooling#2]
Will debug this a bit later, pasting here the traceback:

``` bash
(napalm-test)mircea@36netops3:~/tooling$ ./gh-tools.py label enhancement set "424242"
Skipping repo `napalm`.
Skipping repo `napalm-ansible`.
Label `enhancement` doesn't exist in repo `napalm-base`. Creating.
Traceback (most recent call last):
  File "./gh-tools.py", line 38, in <module>
    cli(obj={})
  File "/state/home/mircea/napalm-test/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/state/home/mircea/napalm-test/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/state/home/mircea/napalm-test/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/state/home/mircea/napalm-test/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/state/home/mircea/napalm-test/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/state/home/mircea/napalm-test/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/state/home/mircea/napalm-test/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/state/home/mircea/tooling/gh_tools/label.py", line 21, in set_label
    ghm.set_label(ctx.obj['name'], color)
  File "/state/home/mircea/tooling/gh_tools/github_helpers.py", line 88, in set_label
    self._set_label_repo(repo, name, color)
  File "/state/home/mircea/tooling/gh_tools/github_helpers.py", line 76, in _set_label_repo
    label = repo.create_label(name, color)
  File "/state/home/mircea/napalm-test/local/lib/python2.7/site-packages/github/Repository.py", line 932, in create_label
    input=post_parameters
  File "/state/home/mircea/napalm-test/local/lib/python2.7/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/state/home/mircea/napalm-test/local/lib/python2.7/site-packages/github/Requester.py", line 180, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/issues/labels/#create-a-label', u'message': u'Not Found'}
```

Or is it a syntax error on my side @dbarrosop?

**Comment by dbarrosop** [comment]
Worked for me:

```
(napalm-tooling) ➜  tooling git:(master) ./gh-tools.py label enhancement set "424242"
Skipping repo `napalm`.
Skipping repo `napalm-ansible`.
Label `enhancement` doesn't exist in repo `napalm-base`. Creating.
Label `enhancement` doesn't exist in repo `napalm-eos`. Creating.
Label `enhancement` already exists in repo `napalm-junos`.
Label `enhancement` doesn't exist in repo `napalm-ios`. Creating.
Label `enhancement` doesn't exist in repo `napalm-iosxr`. Creating.
Label `enhancement` doesn't exist in repo `napalm-fortios`. Creating.
Label `enhancement` doesn't exist in repo `napalm-pluribus`. Creating.
Label `enhancement` doesn't exist in repo `napalm-nxos`. Creating.
Label `enhancement` doesn't exist in repo `napalm-ibm`. Creating.
Skipping repo `napalm-salt`.
Skipping repo `napalm-skeleton`.
Label `enhancement` doesn't exist in repo `napalm-panos`. Creating.
Label `enhancement` doesn't exist in repo `napalm-ros`. Creating.
Label `enhancement` doesn't exist in repo `napalm-snmp`. Creating.
Label `enhancement` doesn't exist in repo `napalm-iosxr-rpc`. Creating.
Skipping repo `iosxr-ez`.
Skipping repo `tooling`.
Label `enhancement` already exists in repo `napalm-vyos` but has a different color. Fixing.
```

I think you might have an issue with your github token.

**Comment by mirceaulinic** [comment]
Oh no :( I thought I set this already in my env. We can close this one.
